name: stactools
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - pip
  - rasterio~=1.2
  - pip:
      - black
      - codespell
      - coverage
      - flake8
      - ipython
      - jupyter
      - lxml-stubs
      - mypy
      - nbsphinx
      - pydata-sphinx-theme
      - pylint
      - sphinx < 6
      - sphinx-autobuild
      - sphinx-click
      - sphinxcontrib-napoleon
      - types-certifi
      - types-orjson
      - types-python-dateutil
      - types-requests
      - .
