name: stactools
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::gdal>=3.10
  - conda-forge::geos>=3.3
  - conda-forge::rasterio>=1.3
  - conda-forge::libgdal-hdf5
  - conda-forge::libgdal-jp2openjpeg
