#!/bin/bash

set -e

if [[ -n "${STACTOOLS_DEBUG}" ]]; then
    set -x
fi

source $(dirname "$0")/env

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Runs CI in the docker dev container.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    ./docker/build
    docker run --rm \
        --entrypoint scripts/cibuild \
        $DOCKER_REGISTRY/$DOCKER_ORG/$DOCKER_REPO:$DOCKER_TAG_DEV
fi
