#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Format code with yapf
"
}

PACKAGES_TO_CHECK=(
    "stactools_core/stactools"
    "stactools_cli/stactools"
    "stactools_landsat/stactools"
    "stactools_planet/stactools"
    "stactools_browse/stactools"
    "tests"
);

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Code formatting
        yapf -ipr ${PACKAGES_TO_CHECK[@]}
    fi
fi
