#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

# Import shared variables
source ./scripts/env

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Install all stactools packages.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        for PACKAGE_DIR in "${STACTOOLS_SUBPACKAGE_DIRS[@]}"
        do
            pushd ./${PACKAGE_DIR}
            pip install -e .
            popd

        done

        pip install -e .[all]
    fi
fi
