#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute project linters and test suites.
"
}

DIRS_TO_CHECK=("tests" "stactools")

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint
        flake8 ${DIRS_TO_CHECK[@]}

        # Code formatting
        yapf -dpr ${DIRS_TO_CHECK[@]}

        # Code spelling
        codespell -I .codespellignore -f \
            scripts/* \
            *.py ./**/*.py \
            *.md \
            docs/*.rst docs/**/*.rst \
            docs/*.ipynb docs/**/*.ipynb

        # Test suite with coverage enabled
        coverage run --source=stactools -m unittest discover tests/
        coverage xml
    fi
fi
