#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Install requirements for all subpackages and development.
"
}

PACKAGES_TO_INSTALL=(
    "stactools_core"
    "stactools_cli"
    "stactools_landsat"
    "stactools_planet"
    "stactools_browse"
);


if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Install/upgrade dependencies
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

        for PACKAGE_DIR in "${PACKAGES_TO_INSTALL[@]}"
        do
            pushd ./${PACKAGE_DIR}
            pip install -r requirements.txt
            popd

        done
    fi
fi
